name: Makefile CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run format
      run: make format
